### ISSUE TITLE
e-bookstore checkout structure

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#2]
```[tasklist]
### Tasks
- [x] header with:
- [x] a company logo
- [x] a search field with a magnifying glass icon and Search placeholder
- [x] 3 icons for user, like, buy cart
- [x] user and buy cart must be links as well
- [x] main containing:
- [x] a products list
- [x] every item inside must have
- [x] - item name
- [x] quantity only if more than one
- [x] price
- [x] link to the product
- [x] buy more button
- [x] a total amount
- [x] billing information
- [x] proceed to checkout button
```
