### ISSUE TITLE
e-bookstore user page structure 

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#3]
```[tasklist]
### Tasks
- [ ] header with:
- [ ] a company logo
- [ ] a search field with a magnifying glass icon and Search placeholder
- [ ] 3 icons for user, like, buy cart
- [ ] user and buy cart must be links as well
- [ ] main with
- [ ] user image
- [ ] user name
- [ ] billing information
- [ ] liked books list
- [ ] buy cart list
- [ ] button linked to home page
- [ ] button linked to buy cart
- [ ] book suggestions
```
