### ISSUE TITLE
e-bookstore single book site structure 

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#4]
```[tasklist]
### Tasks
- [x] header with:
- [x] a company logo
- [x] a search field with a magnifying glass icon and Search placeholder
- [x] 3 icons for user, like, buy cart
- [x] user and buy cart must be links as well
- [ ] main with:
- [ ] book img
- [ ] book title (h1)
- [ ] author
- [ ] Summary h2
- [ ] book description
- [ ] button with book price and Buy Now
- [ ] a like icon
```
