### ISSUE TITLE
e-book store category site structure 

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#5]
```[tasklist]
### Tasks
- [x] header with:
- [x] a company logo
- [x] a search field with a magnifying glass icon and Search placeholder
- [x] 3 icons for user, like, buy cart
- [x] user and buy cart must be links as well
- [x] < button linked to home page
- [x] h1 with the category title
- [x] a main with all the books pertaining to this category
- [x] every book should be a div with the following elements
- [x] book image
- [x] book title
- [x] author
- [x] price
```
