### ISSUE TITLE
format book data

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#54]
```[tasklist]
### Tasks
- [x] only first letter on title must be capitalized
- [ ] first and last name on authors must be capitalized
- [x] price must have a $ after
```
