### ISSUE TITLE
handle contact form

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#55]
```[tasklist]
### Tasks
- [x] test that every required field has a value. (All inputs but text area are required)
- [x] data type must be the expected
- [x] firstName, lastName, and email should NOT be longer than 50 characters, nor shorter than 2
- [x] an email should contain at least an @ and a .
- [x] You may use regex
- [x] in case an input has an incorrect format, the user should get a notification
- [ ] after sanitation every input should be stored in a single object
- [ ] if right, send the content after clicking on the send button
```
