### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#68]
Build a carousel on the Home page.

```[tasklist]
### Tasks
- [ ] the user can click on an arrow icon to slide between images
- [ ] every image has a different text
- [ ] the user can click on bullet points to slide directly to a certain image
- [ ] the carousel has no end: is always possible to keep scrolling right or left
```
