### ISSUE TITLE
e-bookstore signup structure 

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#7]
```[tasklist]
### Tasks
- [ ] an image
- [ ] company logo
- [ ] _sign up for a new account!_ message
- [ ] login to your account message
- [ ] form with
- [ ] Name input and _John Doe_ placeholder_
- [ ] E-mail input and [john@mail.com](mailto:john@mail.com) placeholder
- [ ] password input and 8 bullet points placeholder
- [ ] Remember Me checbox input
```
