### ISSUE TITLE
e-bookstore home page structure 

### ISSUE THREAD

**Issue by AlbertLeipzig** [WD23-D04/e-bookstore#8]
```[tasklist]
### Tasks
- [x] a header with:
- [x] a company logo
- [x] a search field with a magnifying glass icon and Search placeholder
- [x] 3 icons for user, like, buy cart
- [x] user and buy cart must be links as well
- [x] a hero section carousel section with:
- [x] 3 divs, every each of them with a different img-bg and a different h2 message
- [x] a main containing different sections (one for best seller, classics, ,...), each of them with:
- [x] a section title (h2)
- [x] a View All link that links to the section site
- [x] 4 divs, each of them for a different book, containing:
- [x] book img
- [x] book title
- [x] author
- [x] price
```
